//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_webApiAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int Hotel_ID { get; set; }
        public string hotel_name { get; set; }
        public string hotel_address { get; set; }
        public string hotel_city { get; set; }
        public string hotel_pincode { get; set; }
        public string hotel_mno { get; set; }
        public string hotel_contact_person { get; set; }
        public string website { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    }
}
