//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_webApiAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int Room_Id { get; set; }
        public Nullable<int> Hotel_ID { get; set; }
        public string room_name { get; set; }
        public string room_category { get; set; }
        public Nullable<double> room_price { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
    }
}
